SAR-7387 Create logic for scenario 2
hmrc/claim-vat-enrolment-frontend pull request #49
Opened 2021-04-13 12:57 UTC by EviNikolaidou

2021-04-14 10:58 UTC, kabuumu requested changes

2021-04-14 10:58 UTC, kabuumu commented on app/uk/gov/hmrc/claimvatenrolmentfrontend/models/AllocateEnrolmentResponse.scala
> +        case CONFLICT => MultipleEnrolmentsInvalid(response.body)
I think this needs to check for the specific code MULTIPLE_ENROLMENTS_INVALID coming back. There may be other 409s that mean different things.

2021-04-14 10:58 UTC, kabuumu commented on it/uk/gov/hmrc/claimvatenrolmentfrontend/controllers/CheckYourAnswersControllerISpec.scala
> +      stubAllocateEnrolment(testFullClaimVatEnrolmentModel, testCredentialId, testGroupId)(CONFLICT)
This stub will need updating too.

2021-04-15 12:23 UTC, r-melvin commented on app/uk/gov/hmrc/claimvatenrolmentfrontend/models/AllocateEnrolmentResponse.scala
> +import play.api.http.Status.{CONFLICT, CREATED, _}
This should just be an underscore

2021-04-15 12:38 UTC, merged